### ISSUE TITLE
textdomain in line 316

### ISSUE THREAD

**Issue by lones** [jprieton/wp-bootstrap4-navwalker#1]
Thanks for doing this :) Just uploading wp-bootstrap-navwalker.php to the theme resulted in a white screen here. Replacing '\SourceFramework\TEXTDOMAIN' on line 316 in wp-bootstrap-navwalker.php with 'my-text-domain' worked like a charm. Perhaps include in the introduction, that you have to edit line 316 to show your own textdomain?

**Comment by jprieton** [comment]
I remove the non declared constan in the today commit. 
Thanks!
