### ISSUE TITLE
Parse error

### ISSUE THREAD

**Issue by meherbala** [jprieton/wp-bootstrap4-navwalker#2]
When using the code I am getting a Parse error: syntax error, unexpected '[' in x:\xx\xxx\wp-content\themes\del\wp-bootstrap-navwalker.php on line 126 

Any ideas how to fix it.

**Comment by jprieton** [comment]
Is a array short sintax for PHP 5.4 and above, please check your version of PHP

**Comment by jprieton** [comment]
Rollback to default array declaration

**Comment by jprieton** [comment]
Rollback to default array declaration.
If the problem persists, let me know
