### ISSUE TITLE
Dropdown Issue

### ISSUE THREAD

**Issue by ThomasFontaine** [jprieton/wp-bootstrap4-navwalker#3]
Hello ! I can't use the dropdown menu !
Instead of open the menu, it's just link to the relative page link.

**Comment by jprieton** [comment]
Hello! Have you queued the Bootstrap’s JavaScript? The Dropdown component requires it.
Another point to check is that it is queued after jQuery.

https://getbootstrap.com/docs/4.0/components/dropdowns/

Let me know if the problem was solved, thanks

**Comment by ThomasFontaine** [comment]
Ok… I'm so stupid, i've just forgot all my Js on my new theme.. Thank's mate !
