### ISSUE TITLE
Attribution

### ISSUE THREAD

**Issue by pattonwebz** [jprieton/wp-bootstrap4-navwalker#6]
Hey @jprieton,

I spotted this walker just today when browsing some recommended repos. 

This walker looks very similar to one which I have been maintaining for quite some time: https://github.com/wp-bootstrap/wp-bootstrap-navwalker/

The walker code contains some bugs which existed in the code for many years that I've been aware of for a little while as well as the readme file contains copy/paste code from the repo linked above (again code which I wrote and has typos/formatting issues are exact match for the code at the other repo).

The original walker is GPLv3 or later so you are free to take, use and modify the code as much as you would like. I only ask that you leave the original attribution intact or provide a licence declaration stating where the origin is from.

Thank you :smile:

**Comment by jprieton** [comment]
Yes, you are right, it is based on the version that supports Bootstrap 3.x of your code that I modified to give support to Bootstrap 4.x and be able to use it optionally as a plugin.

I will add a note in the README.md of the repository with a link to your repository.

If you consider the issue closed let me know.

Regards.

**Comment by pattonwebz** [comment]
Hey @jprieton,

This note is plenty sufficient, thank you.

Consider the matter resolved, issue closed :)
